# Generated by Django 5.1.7 on 2025-03-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0005_auto_20200521_2121"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news",
            options={
                "ordering": ("-created",),
                "verbose_name": "News",
                "verbose_name_plural": "News",
            },
        ),
        migrations.RenameField(
            model_name="news",
            old_name="timestamp",
            new_name="created",
        ),
    ]
