# Generated by Django 5.1.7 on 2025-03-14 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0005_alter_user_first_name_alter_user_id"),
    ]

    operations = []
