# Generated by Django 5.1.7 on 2026-03-19 22:18

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_auto_20250314_2038"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="muted_users",
            field=models.ManyToManyField(
                blank=True, related_name="muted_by", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
