# Generated by Django 5.1.7 on 2025-03-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("articles", "0004_alter_article_id"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="article",
            options={
                "ordering": ("-created",),
                "verbose_name": "Article",
                "verbose_name_plural": "Articles",
            },
        ),
        migrations.RenameField(
            model_name="article",
            old_name="timestamp",
            new_name="created",
        ),
    ]
