# Generated by Django 5.1.7 on 2025-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0004_merge_20211109_0225"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="verb",
            field=models.CharField(
                choices=[
                    ("L", "liked"),
                    ("C", "commented"),
                    ("F", "favorited"),
                    ("A", "answered"),
                    ("W", "accepted"),
                    ("E", "edited"),
                    ("K", "also commented"),
                    ("I", "logged in"),
                    ("O", "logged out"),
                    ("V", "voted on"),
                    ("S", "shared"),
                    ("R", "replied to"),
                    ("U", "created an account"),
                    ("X", "followed you"),
                    ("Y", "sent you a friend request"),
                    ("Z", "accepted your friend request"),
                ],
                max_length=1,
            ),
        ),
    ]
