# Generated by Django 5.1.7 on 2025-03-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0005_alter_notification_verb"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="notification",
            options={
                "ordering": ("-created",),
                "verbose_name": "Notification",
                "verbose_name_plural": "Notifications",
            },
        ),
        migrations.RenameField(
            model_name="notification",
            old_name="timestamp",
            new_name="created",
        ),
    ]
