# Generated by Django 5.1.7 on 2025-03-20 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("messager", "0002_auto_20200521_2125"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ("-created",),
                "verbose_name": "Message",
                "verbose_name_plural": "Messages",
            },
        ),
        migrations.RenameField(
            model_name="message",
            old_name="timestamp",
            new_name="created",
        ),
    ]
