# Generated by Django 5.1.7 on 2026-03-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messager", "0003_alter_message_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="message_images/"),
        ),
    ]
