# Generated by Django 5.1.7 on 2026-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messager", "0004_message_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="reaction",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
